# Generated by Django 3.1.5 on 2021-01-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('fileHash', models.CharField(max_length=100)),
                ('download', models.CharField(max_length=100)),
                ('time', models.DateField()),
            ],
        ),
    ]
